"""Shared policy constants."""

MAX_SEMANTIC_CANDIDATES = 500
MAX_RESONANCE_CANDIDATES = 200
RESONANCE_HOP_DECAY = 0.6
RESONANCE_MAX_EDGES_PER_NODE = 8
RESONANCE_CONVERGENCE_CAP = 2.0
LINK_DECAY_HALF_LIFE_DAYS = 90.0
CO_RECALL_WEIGHT_STEP = 0.05
CO_RECALL_WEAKEN_STEP = 0.1
LEGACY_CONTEXT_OWNER = "__legacy_unscoped_context__"
CO_RECALL_INITIAL_WEIGHT = 0.2
NEGATIVE_FEEDBACK_CONFIDENCE_STEP = 0.05
SUPERSEDED_SCORE_PENALTY = 0.4

AUTO_LINK_WEIGHT = 0.3
AUTO_LINK_LIMIT = 5
CONSOLIDATION_MIN_CLUSTER_WEIGHT = 0.6
CONSOLIDATION_MIN_ACTIVATIONS = 3
CONSOLIDATION_MIN_CLUSTER_SIZE = 3
RETENTION_MIN_HALF_LIVES = 4.0

# Federation sync
SYNC_MAX_FUTURE_SKEW_SECONDS = 300
SYNC_HTTP_TIMEOUT_SECONDS = 30
